networks:
  testnet:
    name: testnet
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: ${SUBNET_PREFIX:?SUBNET_PREFIX required}.1
          subnet: ${SUBNET_PREFIX}.0/24
    driver_opts:
      com.docker.network.bridge.name: testnet

services:
  testnet-mysql:
    image: ${IMAGE_PREFIX}/mysql:8.3
    container_name: testnet-mysql
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --max_allowed_packet=128M --default-authentication-plugin=caching_sha2_password --max-connections=500
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "33306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD"
        ]
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 60s

  testnet-redis:
    image: ${IMAGE_PREFIX}/redis:5.0
    container_name: testnet-redis
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.3
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "36379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 1s
      retries: 3

  testnet-es:
    image: ${IMAGE_PREFIX}/elasticsearch:7.10.0
    container_name: testnet-es
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.4
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cat/health || exit 1"
        ]
      interval: 30s
      timeout: 1s
      retries: 3

  testnet-server:
    image: ${IMAGE_PREFIX}/testnet_server:latest
    container_name: testnet-server
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.5
    environment:
      - MYSQL_URL=jdbc:mysql://${SUBNET_PREFIX}.2:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${SUBNET_PREFIX}.3
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ES_HOST=${SUBNET_PREFIX}.4:9200
      - ES_PASSWORD=
      - GPT_ENABLE=${GPT_ENABLE}
      - GPT_KEY=${GPT_KEY}
      - GPT_HOST=${GPT_HOST}
      - TESTNET_API_TOKEN=${TESTNET_API_TOKEN}
    depends_on:
      testnet-mysql:
        condition: service_healthy
      testnet-redis:
        condition: service_healthy
      testnet-es:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --tries=1 --timeout=5 http://localhost:8080/jeecg-boot || exit 1"
        ]
      interval: 30s
      timeout: 1s
      retries: 3
      start_period: 120s
    restart: always

  testnet-frontend:
    container_name: testnet-frontend
    image: ${IMAGE_PREFIX}/testnet_frontend:latest
    networks:
      testnet:
        ipv4_address: ${SUBNET_PREFIX}.6
    ports:
      - "8099:443"
    depends_on:
      testnet-mysql:
        condition: service_healthy
      testnet-redis:
        condition: service_healthy
      testnet-es:
        condition: service_healthy
      testnet-server:
        condition: service_healthy
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -k --silent --fail https://localhost:443 || exit 1"
        ]
      interval: 30s
      timeout: 1s
      retries: 3
