services:
  testnet-client:
    image: ${IMAGE_PREFIX}/testnet_client
    container_name: testnet-client
    volumes:
      - ./data/client_data/tools:/testnet-client/tools
      - ./data/client_data/results:/testnet-client/results
    environment:
      - TESTNET_RESULT_PATH=/testnet-client/results/
      - TESTNET_CLIENT_NAME=testnet-client
      - TESTNET_GRPC_TOKEN=${TESTNET_GRPC_TOKEN}
      - GRPC_ADDRESS=${GRPC_ADDRESS}
    restart: always